name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # or master, depending on your repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read       # for checking out repo
      pages: write         # for deploying Pages
      id-token: write      # REQUIRED for deploy-pages v4

    steps:
      - uses: actions/checkout@v3
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
