name: Deploy LLM Task HTML to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure gh-pages branch exists
        run: |
          git fetch origin
          if ! git show-ref --verify --quiet refs/remotes/origin/gh-pages; then
            git checkout --orphan gh-pages
            git reset --hard
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            echo "<h1>Initializing GitHub Pages...</h1>" > index.html
            git add index.html
            git commit -m "Initialize gh-pages branch"
            git push origin gh-pages
            git checkout main
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Generate HTML
        run: |
          # Run your Python script to generate HTML
          python main.py
          mkdir -p public
          cp index.html public/index.html

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
