name: Deploy GitHub Pages

on:
  push:
    branches:
      - main         # Trigger workflow whenever the main branch is updated

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read   # Required to checkout repo files
      pages: write     # Required to publish to GitHub Pages

    steps:
      - uses: actions/checkout@v3       # Checkout your repo
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4  # Deploy the HTML/CSS/JS files
