name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Change if your default branch is 'master' or something else
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write  # Required for deploy-pages@v4

    steps:
      # Step 1: Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Upload HTML (or other static) files as artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./  # Root of repo; adjust if your HTML is in a subfolder

      # Step 3: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
